In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

ModuleNotFoundError: No module named 'pandas'

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score

In [ ]:
df = pd.read_csv( r"C:\Users\mauri\OneDrive\ドキュメント\ML-Summative\Corruption Perception Data\africa_corruption_dataset.csv")

In [ ]:
df.head(50)

,Country,Year,CPI_Score,Rank,Region,Public_Sector_Corruption,Judicial_Corruption,Police_Corruption,Executive_Branch_Corruption,Legislative_Corruption,...,Government_Effectiveness,Regulatory_Quality,Rule_of_Law,Voice_and_Accountability,GDP_per_Capita,Unemployment_Rate,Inflation_Rate,HDI,Population,Internet_Penetration
0,China,2006,35,115,Europe,3.516350,4.960971,0.526732,0.259013,7.614693,...,6.355944,5.535279,4.331510,0.223406,31544,4.460299,9.210721,0.553672,961715466,83.128712
1,France,2019,49,63,Americas,0.628758,4.609555,2.929108,4.812573,9.180948,...,5.531103,4.045841,4.219997,2.483140,1448,14.571306,8.679824,0.936697,139465783,9.515111
2,UK,2014,89,113,Asia,6.225588,7.083909,2.957661,2.251965,2.179549,...,7.319983,5.716905,2.744201,8.113173,38627,14.506082,1.623418,0.526524,220177765,57.217686
3,Brazil,2010,47,94,Oceania,1.886723,0.897114,1.176462,4.133743,9.256735,...,3.545053,8.765559,3.668047,6.221911,54777,17.803580,3.274039,0.621003,1147467940,51.184013
4,South Africa,2007,86,48,Oceania,5.690436,6.448553,4.047916,8.564265,2.323042,...,3.664303,9.575208,9.023643,2.820733,50994,1.009342,0.105707,0.327575,403794109,66.164296
5,South Africa,2020,96,12,Africa,7.395102,6.163699,2.840287,7.696033,5.300791,...,9.766133,8.380874,0.374725,8.419626,10638,7.051384,6.572326,0.615150,977322903,93.900182
6,France,2006,63,156,Asia,7.836383,2.336196,0.260556,2.419529,3.436220,...,1.188377,1.796817,0.877855,7.351614,60841,0.697339,11.551918,0.888005,66747961,75.176226
7,Japan,2018,31,172,Europe,3.018391,5.423940,8.857208,9.849534,1.145088,...,8.419973,5.917374,9.288448,5.017174,67474,4.207367,6.213779,0.329336,667803585,51.062086
8,Brazil,2022,25,171,Oceania,5.124332,2.222072,8.860190,9.032105,0.528384,...,7.887459,4.447555,2.710002,0.442326,6536,7.992120,14.989994,0.772211,579180425,83.035575
9,South Africa,2010,37,145,Asia,6.209651,1.469230,2.091823,5.286734,3.653465,...,0.541603,4.812647,3.041758,9.063381,38595,2.461401,11.255061,0.570679,70196789,70.166861
10,Brazil,2010,44,40,Africa,8.194807,5.731349,1.628722,5.301503,0.473439,...,7.035024,4.282384,3.440830,6.690819,49653,16.445724,5.623710,0.257239,994597070,89.554708
11,Germany,2023,69,177,Americas,7.613887,9.774743,5.472928,9.012660,1.042064,...,0.938834,0.675571,1.033783,8.134613,9221,4.057629,14.598099,0.391377,1044294120,72.434838
12,Brazil,2020,54,85,Africa,9.879753,2.369333,6.307535,6.361448,1.422976,...,2.105013,8.459017,7.689821,9.358696,56854,8.226763,9.610195,0.357932,593412215,75.301835
13,India,2003,55,57,Africa,0.080847,3.553361,9.575426,5.366884,0.019157,...,9.582142,9.783668,1.631683,1.383425,48577,16.033593,13.791191,0.468433,554496491,8.400015
14,UK,2007,81,87,Asia,4.374894,2.565732,3.773485,7.491485,1.532522,...,3.621505,2.097325,7.017545,7.528387,5357,2.334515,1.310156,0.112768,658510699,0.382092
15,South Africa,2023,64,84,Oceania,2.560445,2.664598,6.182003,2.350971,5.772787,...,0.568018,6.219556,2.325075,1.545635,64838,12.392405,8.363886,0.150869,1135822420,95.561958
16,Brazil,2002,95,121,Asia,1.198934,4.041921,8.781810,8.783774,8.195231,...,5.211981,5.365697,6.821089,5.156345,4054,18.810262,13.626721,0.378436,999743958,25.202838
17,France,2021,94,74,Americas,9.115153,7.018555,4.499538,5.314152,1.934300,...,2.064134,8.964952,9.718730,7.270086,10201,9.085756,9.761963,0.561948,489968176,16.509904
18,USA,2020,35,107,Asia,9.979621,0.388045,1.223458,6.034993,0.808726,...,4.263292,7.041018,5.096976,5.203695,18729,4.802595,14.823178,0.617946,678317255,15.871798
19,India,2001,94,124,Europe,1.805962,9.571242,3.774473,0.899439,7.295142,...,1.016580,7.496619,3.189126,4.725482,3975,18.864018,14.936267,0.910385,683520964,73.789104
20,India,2023,34,100,Africa,0.384334,0.462799,1.365669,3.095090,0.081627,...,0.959689,9.519042,3.779750,2.833550,35448,1.083695,11.880562,0.568917,905329704,4.639855
21,Japan,2011,74,43,Oceania,2.750544,8.812532,0.166395,4.267353,7.341621,...,5.041430,6.634766,3.839240,7.680321,57136,6.231952,4.181485,0.729790,49987462,66.102367
22,Brazil,2005,15,119,Americas,8.348619,8.943781,7.515531,4.139095,1.311172,...,3.358773,4.535576,1.253324,0.893940,68875,16.346707,12.803403,0.481722,1097949695,57.145905
23,Japan,2001,32,23,Africa,2.938901,5.244892,2.384237,7.782844,2.282851,...,1.552703,0.519061,8.187951,2.317234,67294,3.078729,10.552538,0.523363,1390897299,14.730177
24,Japan,2020,73,155,Asia,0.569015,1.369968,0.020070,2.823224,1.200699,...,5.803710,9.063642,3.792316,0.451834,47731,1.681677,1.595105,0.589924,64421170,13.544716
25,USA,2000,96,37,Europe,0.524922,5.651460,8.724324,1.821093,2.473382,...,0.621921,5.897274,7.178939,1.770918,48690,9.160135,5.815165,0.522136,22021716,13.266024
26,Germany,2011,52,134,Asia,4.274228,6.286322,4.437888,5.826173,7.981759,...,7.527388,6.823164,2.703797,4.076478,17227,6.635428,13.117660,0.309432,351285282,25.951838
27,Brazil,2021,32,65,Africa,9.318257,8.577590,2.388599,6.150149,1.325441,...,0.513381,5.052970,3.564029,0.297814,4194,15.943186,10.616439,0.977319,966759415,64.178937
28,China,2011,39,134,Americas,2.859204,5.508954,2.627900,1.215833,9.941656,...,9.703710,3.936232,8.869044,2.268688,46351,6.742893,6.410416,0.618736,906359508,20.688756
29,South Africa,2016,86,178,Oceania,4.271577,4.107094,2.405379,0.024685,3.270978,...,7.356247,5.038875,4.249536,0.406796,12143,13.396502,9.195044,0.346137,904899908,66.007501
30,Japan,2009,27,22,Africa,1.019338,8.382912,1.945562,9.176491,9.219681,...,8.972127,0.485040,3.531840,8.757402,68718,11.203887,14.051679,0.798618,565195268,97.170392
31,UK,2015,96,105,Americas,4.935728,9.809518,8.412262,0.796370,1.900331,...,4.399491,7.979124,3.136599,8.899905,14584,11.939860,8.964313,0.163768,262531941,86.209690
32,Russia,2014,88,88,Africa,6.965471,6.451032,1.703316,8.978669,1.878975,...,0.580810,1.579706,8.929358,6.985269,38402,10.222833,3.415105,0.992524,760630989,79.807815
33,UK,2014,30,153,Europe,2.711504,8.743870,5.618547,3.992149,5.653357,...,2.294401,3.326623,4.228403,5.945078,32804,2.709215,10.040451,0.788800,196129392,94.913583
34,USA,2018,66,125,Asia,2.967113,5.987351,0.773202,6.530559,0.506001,...,9.710950,0.869946,8.771361,7.958424,8439,1.240677,3.992890,0.097478,332819637,61.247182
35,USA,2011,32,79,Oceania,8.419750,6.897880,9.495214,1.856147,8.010029,...,6.188916,8.199463,3.002888,2.814496,38781,10.877969,9.285232,0.848271,1242404318,76.886365
36,France,2022,54,90,Americas,0.103637,6.881671,6.033139,8.239170,4.396153,...,2.278717,1.683438,9.783036,7.420273,35615,12.988476,9.668530,0.258568,1197620747,77.392705
37,Germany,2019,53,51,Oceania,6.364707,7.047870,9.031525,1.801934,6.991965,...,4.828176,3.989194,5.027999,3.301855,26944,14.506570,5.423028,0.637827,1365018593,97.454002
38,South Africa,2002,91,176,Oceania,3.938846,3.210134,3.978778,3.865091,1.746322,...,3.174414,4.154775,1.646212,4.429324,66199,14.442813,11.110162,0.165140,1261520639,64.717651
39,Japan,2004,97,102,Oceania,2.983805,5.756614,8.106721,2.380258,6.423574,...,4.897177,3.164263,4.240703,9.800616,62835,14.806235,4.393647,0.710755,618614070,27.305637
40,UK,2018,56,106,Americas,6.575938,5.941356,8.536545,8.375060,5.940707,...,8.366242,8.601253,6.817677,8.458338,67502,0.406440,0.220857,0.757383,439315887,19.567393
41,Russia,2006,49,60,Americas,8.346685,3.150716,7.029493,8.583358,7.556613,...,2.225555,7.717818,8.878305,4.186595,38035,4.469958,5.259751,0.851579,523869996,30.669435
42,USA,2020,60,46,Oceania,5.583921,3.498524,0.929475,3.720289,2.974013,...,3.990880,7.436778,1.270857,9.050352,5984,14.591825,12.934502,0.487802,762649246,76.175309
43,USA,2008,51,36,Asia,0.310946,7.622468,0.160801,3.073785,9.331656,...,4.460900,2.251170,5.584443,0.972825,12760,2.471636,8.652927,0.553460,897909119,65.655352
44,Germany,2006,16,166,Africa,4.614012,5.827238,1.685597,7.735654,9.613011,...,5.870534,1.895198,5.326475,9.028923,40500,3.731615,12.740576,0.215004,475617356,21.925386
45,Russia,2017,59,11,Oceania,4.627599,1.492111,1.180968,8.785120,8.681236,...,0.777285,2.465941,3.283686,8.892828,26309,13.192043,1.928997,0.515697,811517753,85.983160
46,Russia,2003,57,12,Europe,5.437985,8.376370,7.251377,6.240200,5.720338,...,2.070116,3.861623,4.085803,6.467917,64716,16.163561,2.894846,0.531823,565765834,98.133448
47,Germany,2013,93,170,Oceania,6.709589,8.831143,5.570068,9.274037,4.202883,...,3.978327,4.787566,3.046077,3.246917,23874,3.249632,2.469296,0.809232,1349885294,75.721038
48,USA,2017,15,39,Americas,0.193184,4.661411,5.259509,3.830438,0.579924,...,8.093407,2.501736,3.023979,8.221935,35996,11.016551,11.776905,0.711233,530283835,6.210487
49,South Africa,2008,18,139,Africa,5.020126,2.089074,2.528673,1.518864,9.472278,...,1.868421,4.577621,5.333742,2.721682,17180,3.626886,9.182905,0.698290,359834736,62.754360

In [ ]:
df.tail()

,Country,Year,CPI_Score,Rank,Region,Public_Sector_Corruption,Judicial_Corruption,Police_Corruption,Executive_Branch_Corruption,Legislative_Corruption,...,Government_Effectiveness,Regulatory_Quality,Rule_of_Law,Voice_and_Accountability,GDP_per_Capita,Unemployment_Rate,Inflation_Rate,HDI,Population,Internet_Penetration
2995,USA,2005,86,72,Europe,2.330331,1.966320,5.315040,6.668195,7.064833,...,0.593465,2.274272,9.759258,8.259252,33045,5.625374,14.360683,0.626747,686020267,45.293199
2996,India,2014,36,73,Americas,9.298011,2.681467,1.438198,4.796272,8.712173,...,9.890949,4.758299,6.011689,0.677080,43987,9.971221,1.258015,0.029109,238808995,88.619985
2997,China,2017,87,71,Europe,8.674231,3.304477,8.250303,4.741501,7.480777,...,9.469918,1.376093,8.442582,4.428952,34570,6.765911,8.007051,0.156282,781325985,20.315589
2998,USA,2023,33,78,Europe,0.182053,4.745464,7.359749,3.418901,7.033945,...,6.407382,3.878798,1.039559,4.304439,22506,5.924927,10.561845,0.370743,1337966559,10.378917
2999,Brazil,2010,76,28,Africa,1.285681,0.693517,5.300931,1.069818,7.155596,...,9.142108,3.820346,4.371468,6.208179,18567,8.943194,0.980060,0.446820,1336691611,78.479009

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 33 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Country                      3000 non-null   object
 1   Year                         3000 non-null   int64
 2   CPI_Score                    3000 non-null   int64
 3   Rank                         3000 non-null   int64
 4   Region                       3000 non-null   object
 5   Public_Sector_Corruption     3000 non-null   float64
 6   Judicial_Corruption          3000 non-null   float64
 7   Police_Corruption            3000 non-null   float64
 8   Executive_Branch_Corruption  3000 non-null   float64
 9   Legislative_Corruption       3000 non-null   float64
 10  Bribery_Index                3000 non-null   float64
 11  Business_Corruption          3000 non-null   float64
 12  Health_Corruption            3000 non-null   float64
 13  Education_Corruption         3000 non-null   float64
 14  Media_Corruption             3000 non-null   float64
 15  Political_Party_Corruption   3000 non-null   float64
 16  Foreign_Influence            3000 non-null   float64
 17  Corporate_Governance         3000 non-null   float64
 18  Transparency_Index           3000 non-null   float64
 19  Freedom_of_Press             3000 non-null   float64
 20  Civil_Liberties              3000 non-null   float64
 21  Democracy_Index              3000 non-null   float64
 22  Human_Rights_Index           3000 non-null   float64
 23  Government_Effectiveness     3000 non-null   float64
 24  Regulatory_Quality           3000 non-null   float64
 25  Rule_of_Law                  3000 non-null   float64
 26  Voice_and_Accountability     3000 non-null   float64
 27  GDP_per_Capita               3000 non-null   int64
 28  Unemployment_Rate            3000 non-null   float64
 29  Inflation_Rate               3000 non-null   float64
 30  HDI                          3000 non-null   float64
 31  Population                   3000 non-null   int64
 32  Internet_Penetration         3000 non-null   float64
dtypes: float64(26), int64(5), object(2)
memory usage: 773.6+ KB

In [ ]:
df.isnull().sum()

Country                        0
Year                           0
CPI_Score                      0
Rank                           0
Region                         0
Public_Sector_Corruption       0
Judicial_Corruption            0
Police_Corruption              0
Executive_Branch_Corruption    0
Legislative_Corruption         0
Bribery_Index                  0
Business_Corruption            0
Health_Corruption              0
Education_Corruption           0
Media_Corruption               0
Political_Party_Corruption     0
Foreign_Influence              0
Corporate_Governance           0
Transparency_Index             0
Freedom_of_Press               0
Civil_Liberties                0
Democracy_Index                0
Human_Rights_Index             0
Government_Effectiveness       0
Regulatory_Quality             0
Rule_of_Law                    0
Voice_and_Accountability       0
GDP_per_Capita                 0
Unemployment_Rate              0
Inflation_Rate                 0
HDI                            0
Population                     0
Internet_Penetration           0
dtype: int64

In [ ]:
(df.isnull().sum() / len(df)) * 100

Country                        0.0
Year                           0.0
CPI_Score                      0.0
Rank                           0.0
Region                         0.0
Public_Sector_Corruption       0.0
Judicial_Corruption            0.0
Police_Corruption              0.0
Executive_Branch_Corruption    0.0
Legislative_Corruption         0.0
Bribery_Index                  0.0
Business_Corruption            0.0
Health_Corruption              0.0
Education_Corruption           0.0
Media_Corruption               0.0
Political_Party_Corruption     0.0
Foreign_Influence              0.0
Corporate_Governance           0.0
Transparency_Index             0.0
Freedom_of_Press               0.0
Civil_Liberties                0.0
Democracy_Index                0.0
Human_Rights_Index             0.0
Government_Effectiveness       0.0
Regulatory_Quality             0.0
Rule_of_Law                    0.0
Voice_and_Accountability       0.0
GDP_per_Capita                 0.0
Unemployment_Rate              0.0
Inflation_Rate                 0.0
HDI                            0.0
Population                     0.0
Internet_Penetration           0.0
dtype: float64

In [ ]:
df.describe()

,Year,CPI_Score,Rank,Public_Sector_Corruption,Judicial_Corruption,Police_Corruption,Executive_Branch_Corruption,Legislative_Corruption,Bribery_Index,Business_Corruption,...,Government_Effectiveness,Regulatory_Quality,Rule_of_Law,Voice_and_Accountability,GDP_per_Capita,Unemployment_Rate,Inflation_Rate,HDI,Population,Internet_Penetration
count,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,...,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3.000000e+03,3000.000000
mean,2011.435000,54.912333,88.424333,5.010192,4.993386,4.958386,4.980443,5.074054,5.072599,5.002190,...,4.962047,4.979749,4.999241,4.942573,35516.944333,10.038021,7.409798,0.503730,6.991307e+08,49.822329
std,7.009338,26.157052,51.073076,2.876792,2.847876,2.899674,2.884999,2.930100,2.854116,2.862607,...,2.905259,2.921780,2.884855,2.906419,20106.945250,5.685558,4.309502,0.286330,3.985334e+08,28.729558
min,2000.000000,10.000000,1.000000,0.001186,0.001755,0.000093,0.009650,0.002014,0.000205,0.002480,...,0.001151,0.001459,0.006938,0.001751,668.000000,0.005592,0.015429,0.000860,7.681120e+05,0.010092
25%,2005.000000,32.000000,45.000000,2.538800,2.558983,2.406181,2.499116,2.563307,2.647457,2.551592,...,2.429524,2.433208,2.525841,2.445547,17897.250000,5.214202,3.733927,0.257157,3.576168e+08,24.567703
50%,2011.500000,55.000000,86.000000,5.065921,4.978829,4.944483,4.871549,5.106205,5.176887,5.033025,...,4.917971,4.966884,4.984914,4.859661,36060.500000,10.027623,7.308117,0.510571,7.037099e+08,50.775874
75%,2018.000000,78.000000,132.000000,7.474694,7.365100,7.444565,7.533397,7.621012,7.507742,7.472539,...,7.517343,7.609392,7.521666,7.387475,52863.000000,14.846671,11.078370,0.753903,1.037071e+09,74.346050
max,2023.000000,99.000000,179.000000,9.998167,9.998927,9.996948,9.995181,9.998911,9.999739,9.998393,...,9.996570,9.996766,9.998929,9.998867,69966.000000,19.994069,14.994429,0.999322,1.399928e+09,99.941563

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df[["Country", "Region", "Government_Effectiveness", "Rule_of_Law", "Unemployment_Rate", "GDP_per_Capita"]]

,Country,Region,Government_Effectiveness,Rule_of_Law,Unemployment_Rate,GDP_per_Capita
0,China,Europe,6.355944,4.331510,4.460299,31544
1,France,Americas,5.531103,4.219997,14.571306,1448
2,UK,Asia,7.319983,2.744201,14.506082,38627
3,Brazil,Oceania,3.545053,3.668047,17.803580,54777
4,South Africa,Oceania,3.664303,9.023643,1.009342,50994
...,...,...,...,...,...,...
2995,USA,Europe,0.593465,9.759258,5.625374,33045
2996,India,Americas,9.890949,6.011689,9.971221,43987
2997,China,Europe,9.469918,8.442582,6.765911,34570
2998,USA,Europe,6.407382,1.039559,5.924927,22506
2999,Brazil,Africa,9.142108,4.371468,8.943194,18567

In [ ]:
correlation = df.corr(numeric_only=True)
print(correlation)

                                 Year  CPI_Score      Rank  \
Year                         1.000000   0.025397 -0.036180
CPI_Score                    0.025397   1.000000 -0.012124
Rank                        -0.036180  -0.012124  1.000000
Public_Sector_Corruption    -0.005280  -0.011414  0.002764
Judicial_Corruption         -0.013728  -0.007187 -0.028034
Police_Corruption            0.000056   0.028988  0.016022
Executive_Branch_Corruption  0.011178   0.005888 -0.038784
Legislative_Corruption      -0.005180  -0.011026 -0.025096
Bribery_Index               -0.002847  -0.001492  0.003127
Business_Corruption          0.022161  -0.020747 -0.006700
Health_Corruption           -0.012954  -0.007128 -0.023761
Education_Corruption         0.013211   0.016985 -0.005943
Media_Corruption            -0.013178  -0.016520 -0.014067
Political_Party_Corruption   0.012158  -0.032155  0.009194
Foreign_Influence           -0.016254   0.010311 -0.002821
Corporate_Governance         0.033050   0.001467 -0.022049
Transparency_Index           0.010882   0.014812  0.010537
Freedom_of_Press            -0.014230  -0.016636  0.003400
Civil_Liberties              0.009665   0.038286 -0.016563
Democracy_Index              0.015188   0.010928  0.021530
Human_Rights_Index          -0.001821  -0.008620 -0.025938
Government_Effectiveness    -0.002108  -0.016339  0.002100
Regulatory_Quality           0.000367  -0.002572  0.006565
Rule_of_Law                 -0.000636   0.015347 -0.011289
Voice_and_Accountability    -0.010067   0.009979  0.015007
GDP_per_Capita              -0.032435   0.017189  0.020807
Unemployment_Rate           -0.009254   0.008076  0.012475
Inflation_Rate               0.013689  -0.010292 -0.009241
HDI                          0.032541   0.012222 -0.006769
Population                  -0.003458   0.011118 -0.010471
Internet_Penetration         0.008320   0.012293  0.016807

                             Public_Sector_Corruption  Judicial_Corruption  \
Year                                        -0.005280            -0.013728
CPI_Score                                   -0.011414            -0.007187
Rank                                         0.002764            -0.028034
Public_Sector_Corruption                     1.000000            -0.046108
Judicial_Corruption                         -0.046108             1.000000
Police_Corruption                            0.013276             0.008299
Executive_Branch_Corruption                  0.007993             0.016799
Legislative_Corruption                       0.014864            -0.019859
Bribery_Index                               -0.019680            -0.002422
Business_Corruption                          0.001684            -0.000677
Health_Corruption                           -0.003747             0.016874
Education_Corruption                         0.000894             0.003338
Media_Corruption                            -0.003195            -0.002189
Political_Party_Corruption                  -0.009483            -0.013466
Foreign_Influence                            0.014741             0.005264
Corporate_Governance                         0.020684            -0.006396
Transparency_Index                          -0.022241             0.021026
Freedom_of_Press                             0.027715            -0.009712
Civil_Liberties                             -0.016393            -0.011806
Democracy_Index                             -0.026704             0.026488
Human_Rights_Index                           0.041599             0.005183
Government_Effectiveness                    -0.003379            -0.040355
Regulatory_Quality                          -0.001533            -0.004176
Rule_of_Law                                 -0.010305             0.031593
Voice_and_Accountability                    -0.006701            -0.012409
GDP_per_Capita                              -0.009371            -0.019081
Unemployment_Rate                           -0.004961             0.015821
Inflation_Rate                              -0.019879             0.030453
HDI                                          0.008557             0.033734
Population                                  -0.017841             0.009534
Internet_Penetration                         0.008182            -0.005043

                             Police_Corruption  Executive_Branch_Corruption  \
Year                                  0.000056                     0.011178
CPI_Score                             0.028988                     0.005888
Rank                                  0.016022                    -0.038784
Public_Sector_Corruption              0.013276                     0.007993
Judicial_Corruption                   0.008299                     0.016799
Police_Corruption                     1.000000                    -0.027914
Executive_Branch_Corruption          -0.027914                     1.000000
Legislative_Corruption                0.027066                     0.000920
Bribery_Index                         0.010288                     0.001995
Business_Corruption                  -0.047374                     0.009662
Health_Corruption                    -0.031226                    -0.000772
Education_Corruption                 -0.018098                    -0.008421
Media_Corruption                     -0.012494                     0.008360
Political_Party_Corruption            0.006569                    -0.002394
Foreign_Influence                    -0.006492                    -0.023625
Corporate_Governance                 -0.010681                    -0.015770
Transparency_Index                   -0.015687                     0.005736
Freedom_of_Press                     -0.022722                     0.017390
Civil_Liberties                      -0.001382                     0.028622
Democracy_Index                       0.020977                     0.020443
Human_Rights_Index                    0.038841                     0.008295
Government_Effectiveness              0.029970                    -0.025681
Regulatory_Quality                   -0.014311                    -0.006739
Rule_of_Law                          -0.043490                    -0.025799
Voice_and_Accountability              0.019438                    -0.022349
GDP_per_Capita                        0.044267                     0.007660
Unemployment_Rate                     0.003764                     0.012923
Inflation_Rate                        0.013187                     0.028068
HDI                                  -0.002503                    -0.017068
Population                           -0.020576                     0.027230
Internet_Penetration                  0.005905                     0.021775

                             Legislative_Corruption  Bribery_Index  \
Year                                      -0.005180      -0.002847
CPI_Score                                 -0.011026      -0.001492
Rank                                      -0.025096       0.003127
Public_Sector_Corruption                   0.014864      -0.019680
Judicial_Corruption                       -0.019859      -0.002422
Police_Corruption                          0.027066       0.010288
Executive_Branch_Corruption                0.000920       0.001995
Legislative_Corruption                     1.000000      -0.014795
Bribery_Index                             -0.014795       1.000000
Business_Corruption                       -0.011631       0.023091
Health_Corruption                         -0.000828       0.014574
Education_Corruption                      -0.028845       0.003604
Media_Corruption                          -0.003995       0.016614
Political_Party_Corruption                 0.013682      -0.000056
Foreign_Influence                          0.015445       0.015249
Corporate_Governance                       0.006161       0.033312
Transparency_Index                        -0.020638       0.019569
Freedom_of_Press                          -0.006112      -0.002383
Civil_Liberties                           -0.024907       0.004527
Democracy_Index                           -0.022191       0.003213
Human_Rights_Index                        -0.056475      -0.004071
Government_Effectiveness                  -0.007940      -0.014908
Regulatory_Quality                        -0.017704      -0.000071
Rule_of_Law                                0.006816      -0.007483
Voice_and_Accountability                   0.002877      -0.000339
GDP_per_Capita                             0.015936       0.006329
Unemployment_Rate                         -0.016597       0.008770
Inflation_Rate                            -0.018387      -0.006651
HDI                                        0.017635      -0.026914
Population                                -0.016490      -0.018006
Internet_Penetration                      -0.001473      -0.019814

                             Business_Corruption  ...  \
Year                                    0.022161  ...
CPI_Score                              -0.020747  ...
Rank                                   -0.006700  ...
Public_Sector_Corruption                0.001684  ...
Judicial_Corruption                    -0.000677  ...
Police_Corruption                      -0.047374  ...
Executive_Branch_Corruption             0.009662  ...
Legislative_Corruption                 -0.011631  ...
Bribery_Index                           0.023091  ...
Business_Corruption                     1.000000  ...
Health_Corruption                      -0.024854  ...
Education_Corruption                    0.006782  ...
Media_Corruption                        0.012503  ...
Political_Party_Corruption              0.006925  ...
Foreign_Influence                      -0.017853  ...
Corporate_Governance                   -0.012287  ...
Transparency_Index                      0.022736  ...
Freedom_of_Press                        0.021437  ...
Civil_Liberties                        -0.018209  ...
Democracy_Index                         0.032148  ...
Human_Rights_Index                      0.020179  ...
Government_Effectiveness               -0.000104  ...
Regulatory_Quality                     -0.001076  ...
Rule_of_Law                            -0.023683  ...
Voice_and_Accountability               -0.000598  ...
GDP_per_Capita                         -0.010624  ...
Unemployment_Rate                      -0.001847  ...
Inflation_Rate                          0.010295  ...
HDI                                    -0.012886  ...
Population                             -0.003356  ...
Internet_Penetration                    0.023052  ...

                             Government_Effectiveness  Regulatory_Quality  \
Year                                        -0.002108            0.000367
CPI_Score                                   -0.016339           -0.002572
Rank                                         0.002100            0.006565
Public_Sector_Corruption                    -0.003379           -0.001533
Judicial_Corruption                         -0.040355           -0.004176
Police_Corruption                            0.029970           -0.014311
Executive_Branch_Corruption                 -0.025681           -0.006739
Legislative_Corruption                      -0.007940           -0.017704
Bribery_Index                               -0.014908           -0.000071
Business_Corruption                         -0.000104           -0.001076
Health_Corruption                           -0.016003            0.027050
Education_Corruption                        -0.011585            0.017944
Media_Corruption                            -0.019584            0.021187
Political_Party_Corruption                   0.004780           -0.028664
Foreign_Influence                           -0.027076           -0.021964
Corporate_Governance                        -0.034647            0.004374
Transparency_Index                           0.007898           -0.008135
Freedom_of_Press                            -0.008227            0.012457
Civil_Liberties                             -0.022211           -0.007459
Democracy_Index                             -0.005096           -0.039270
Human_Rights_Index                          -0.011775           -0.047491
Government_Effectiveness                     1.000000           -0.025364
Regulatory_Quality                          -0.025364            1.000000
Rule_of_Law                                 -0.018325            0.011968
Voice_and_Accountability                    -0.032750            0.008757
GDP_per_Capita                               0.020466            0.022156
Unemployment_Rate                            0.012329           -0.012485
Inflation_Rate                              -0.004665            0.031117
HDI                                          0.006922            0.011304
Population                                   0.013561           -0.031787
Internet_Penetration                        -0.009146           -0.000362

                             Rule_of_Law  Voice_and_Accountability  \
Year                           -0.000636                 -0.010067
CPI_Score                       0.015347                  0.009979
Rank                           -0.011289                  0.015007
Public_Sector_Corruption       -0.010305                 -0.006701
Judicial_Corruption             0.031593                 -0.012409
Police_Corruption              -0.043490                  0.019438
Executive_Branch_Corruption    -0.025799                 -0.022349
Legislative_Corruption          0.006816                  0.002877
Bribery_Index                  -0.007483                 -0.000339
Business_Corruption            -0.023683                 -0.000598
Health_Corruption               0.010894                 -0.021053
Education_Corruption           -0.006955                  0.020278
Media_Corruption               -0.011727                 -0.002133
Political_Party_Corruption      0.012878                  0.039280
Foreign_Influence               0.004645                  0.000373
Corporate_Governance            0.027207                  0.011508
Transparency_Index             -0.012519                 -0.002515
Freedom_of_Press               -0.027237                  0.019059
Civil_Liberties                 0.011265                 -0.002203
Democracy_Index                 0.018442                  0.003129
Human_Rights_Index             -0.017043                  0.029240
Government_Effectiveness       -0.018325                 -0.032750
Regulatory_Quality              0.011968                  0.008757
Rule_of_Law                     1.000000                  0.025568
Voice_and_Accountability        0.025568                  1.000000
GDP_per_Capita                 -0.037219                 -0.010489
Unemployment_Rate               0.021735                  0.008248
Inflation_Rate                  0.015956                 -0.044783
HDI                            -0.003167                  0.020375
Population                      0.019830                 -0.014898
Internet_Penetration           -0.014068                  0.000411

                             GDP_per_Capita  Unemployment_Rate  \
Year                              -0.032435          -0.009254
CPI_Score                          0.017189           0.008076
Rank                               0.020807           0.012475
Public_Sector_Corruption          -0.009371          -0.004961
Judicial_Corruption               -0.019081           0.015821
Police_Corruption                  0.044267           0.003764
Executive_Branch_Corruption        0.007660           0.012923
Legislative_Corruption             0.015936          -0.016597
Bribery_Index                      0.006329           0.008770
Business_Corruption               -0.010624          -0.001847
Health_Corruption                 -0.005779          -0.003939
Education_Corruption               0.021315           0.020035
Media_Corruption                  -0.019983           0.032885
Political_Party_Corruption        -0.011339           0.023668
Foreign_Influence                 -0.033566          -0.014381
Corporate_Governance              -0.010314           0.002855
Transparency_Index                 0.010402          -0.007433
Freedom_of_Press                   0.015908           0.007266
Civil_Liberties                    0.019951          -0.020127
Democracy_Index                    0.007785           0.004431
Human_Rights_Index                -0.024863          -0.008500
Government_Effectiveness           0.020466           0.012329
Regulatory_Quality                 0.022156          -0.012485
Rule_of_Law                       -0.037219           0.021735
Voice_and_Accountability          -0.010489           0.008248
GDP_per_Capita                     1.000000          -0.048427
Unemployment_Rate                 -0.048427           1.000000
Inflation_Rate                    -0.047847           0.017291
HDI                               -0.026231           0.049759
Population                         0.008298           0.033832
Internet_Penetration               0.012801           0.002241

                             Inflation_Rate       HDI  Population  \
Year                               0.013689  0.032541   -0.003458
CPI_Score                         -0.010292  0.012222    0.011118
Rank                              -0.009241 -0.006769   -0.010471
Public_Sector_Corruption          -0.019879  0.008557   -0.017841
Judicial_Corruption                0.030453  0.033734    0.009534
Police_Corruption                  0.013187 -0.002503   -0.020576
Executive_Branch_Corruption        0.028068 -0.017068    0.027230
Legislative_Corruption            -0.018387  0.017635   -0.016490
Bribery_Index                     -0.006651 -0.026914   -0.018006
Business_Corruption                0.010295 -0.012886   -0.003356
Health_Corruption                  0.025596 -0.013282   -0.002323
Education_Corruption              -0.021255 -0.000413    0.000091
Media_Corruption                  -0.011370 -0.019305   -0.002745
Political_Party_Corruption        -0.045439  0.041221   -0.037824
Foreign_Influence                 -0.008147  0.006250   -0.015704
Corporate_Governance              -0.024337 -0.018316   -0.004898
Transparency_Index                 0.020962 -0.015942   -0.018419
Freedom_of_Press                  -0.014740 -0.011596    0.003271
Civil_Liberties                   -0.022784  0.024701   -0.042811
Democracy_Index                   -0.011567  0.029914    0.015266
Human_Rights_Index                 0.021743 -0.008682   -0.019888
Government_Effectiveness          -0.004665  0.006922    0.013561
Regulatory_Quality                 0.031117  0.011304   -0.031787
Rule_of_Law                        0.015956 -0.003167    0.019830
Voice_and_Accountability          -0.044783  0.020375   -0.014898
GDP_per_Capita                    -0.047847 -0.026231    0.008298
Unemployment_Rate                  0.017291  0.049759    0.033832
Inflation_Rate                     1.000000 -0.007018   -0.014255
HDI                               -0.007018  1.000000    0.020546
Population                        -0.014255  0.020546    1.000000
Internet_Penetration              -0.019367  0.017587    0.017449

                             Internet_Penetration
Year                                     0.008320
CPI_Score                                0.012293
Rank                                     0.016807
Public_Sector_Corruption                 0.008182
Judicial_Corruption                     -0.005043
Police_Corruption                        0.005905
Executive_Branch_Corruption              0.021775
Legislative_Corruption                  -0.001473
Bribery_Index                           -0.019814
Business_Corruption                      0.023052
Health_Corruption                        0.026070
Education_Corruption                    -0.015068
Media_Corruption                         0.002931

In [ ]:
correlation["Judicial_Corruption"].sort_values(ascending=False)

Judicial_Corruption            1.000000
HDI                            0.033734
Rule_of_Law                    0.031593
Inflation_Rate                 0.030453
Democracy_Index                0.026488
Transparency_Index             0.021026
Health_Corruption              0.016874
Executive_Branch_Corruption    0.016799
Unemployment_Rate              0.015821
Population                     0.009534
Police_Corruption              0.008299
Foreign_Influence              0.005264
Human_Rights_Index             0.005183
Education_Corruption           0.003338
Business_Corruption           -0.000677
Media_Corruption              -0.002189
Bribery_Index                 -0.002422
Regulatory_Quality            -0.004176
Internet_Penetration          -0.005043
Corporate_Governance          -0.006396
CPI_Score                     -0.007187
Freedom_of_Press              -0.009712
Civil_Liberties               -0.011806
Voice_and_Accountability      -0.012409
Political_Party_Corruption    -0.013466
Year                          -0.013728
GDP_per_Capita                -0.019081
Legislative_Corruption        -0.019859
Rank                          -0.028034
Government_Effectiveness      -0.040355
Public_Sector_Corruption      -0.046108
Name: Judicial_Corruption, dtype: float64

In [ ]:
features = [
    "CPI_Score",
    "Government_Effectiveness",
    "Rule_of_Law",
    "Transparency_Index",
    "Democracy_Index",
    "GDP_per_Capita",
    "HDI",
    "Voice_and_Accountability",
    "Regulatory_Quality",
    "Freedom_of_Press",
    "Unemployment_Rate"
]

In [ ]:
heatmap_columns = [
    "CPI_Score",
    "Government_Effectiveness",
    "Rule_of_Law",
    "Transparency_Index",
    "Democracy_Index",
    "GDP_per_Capita",
    "HDI",
    "Voice_and_Accountability",
    "Regulatory_Quality",
    "Freedom_of_Press",
    "Unemployment_Rate"
]

corr = df[heatmap_columns].corr()

NameError: name 'df' is not defined

In [ ]:
import matplotlib.pyplot as plt

plt.figure(figsize=(11,9))

plt.imshow(corr, cmap="coolwarm")

plt.colorbar(label="Correlation")

plt.xticks(range(len(corr.columns)), corr.columns,
           rotation=90)

plt.yticks(range(len(corr.columns)), corr.columns)

# Add correlation values
for i in range(len(corr.columns)):
    for j in range(len(corr.columns)):
        plt.text(
            j,
            i,
            f"{corr.iloc[i,j]:.2f}",
            ha="center",
            va="center",
            fontsize=8
        )

plt.title("Correlation Heatmap of Selected Features")

plt.tight_layout()

plt.show()

ModuleNotFoundError: No module named 'matplotlib'